name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
#      - name: Install prerequisites
#        run: ci/install.sh
      - name: NPM install
        run: npm ci
#      - name: Build
#        run: source emsdk/emsdk_env.sh && ./build.sh
#      - name: Test
#        run: npm test
      - name: Prepare deployment
        id: prepare-deployment
        run: npm run prepare-deployment
      - name: Package
        run: npm pack
      - name: Upload to Bintray
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: argon2-browser-${{ steps.prepare-deployment.outputs.package-version }}.tgz
          api_user: antelle
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: antelle
          repository: generic
          package: argon2-browser
          version: ${{ steps.prepare-deployment.outputs.bintray-version }}
          upload_path: ${{ steps.prepare-deployment.outputs.upload-path }}
          publish: 1
          calculate_metadata: false